version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: alealevan/reverseproxy 
  backend_user:
    build:
      context: ../../udacity-c3-restapi-user
    image: alealevan/udacity-udagram-user
  backend_feed:
    build:
      context: ../../udacity-c3-restapi-feed  
    image: alealevan/udacity-udagram-feed
  frontend:
    build:
      context: ../../udacity-c3-frontend  
    image: alealevan/udacity-udagram-frontend
